### ISSUE TITLE
Fix PR for kernel 6.12.22 and merge it

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/gardenlinux#2949]
The patches don't apply

Open PR: https://github.com/gardenlinux/package-linux/pull/104/files

Workflow run: https://github.com/gardenlinux/package-linux/actions/runs/14310254585/job/40103270890

```
++ read -r patch
++ cd /tmp/tmp.bd0ay9QZGT/src
++ patch -p1
patching file debian/patches/debian/gitignore.patch
Hunk #1 FAILED at 10.
Hunk #2 FAILED at 22.
Hunk #3 FAILED at 42.
3 out of 3 hunks FAILED -- saving rejects to file debian/patches/debian/gitignore.patch.rej
+ cd /
+ rm -rf /tmp/tmp.bd0ay9QZGT
Error: Process completed with exit code 1.
```

**Comment by Vincinator** [comment]
Fix it for training purposes, or wait for debian salsa to fix it.
6.12 is currently in debian/trixie so should not take forever for a fix from debian. 

Let me know if this is urgent and I should fix the patch.

**Comment by fwilhe** [comment]
Yes. Just FYI I've already bumped to the latest 6.12 tag of the debian kernel build (as of Monday), that did not resolve it, but also that patch version is off by one.

<img width="499" alt="Image" src="https://github.com/user-attachments/assets/37004d96-ac16-4941-87a8-c996535d30f7" />
